---

- name: Check if psql (postgres) exists
  shell: "psql --version"
  register: pg_current_major_raw
  become_user: postgres
  ignore_errors: yes

- name: Check for ndodbadmin user in PostgreSQL
  shell: "psql -tAc \"SELECT 1 FROM pg_roles WHERE rolname='ndodbadmin'\""
  register: ndodbadmin_user
  become_user: postgres
  ignore_errors: yes

- set_fact:
    fresh_install: false

- set_fact:
    fresh_install: true
  when: pg_current_major_raw.failed or ndodbadmin_user.stdout == ""

- debug:
    var: fresh_install

- name: Install postgres if necessary
  include_tasks: install_postgres.yml
  when:  fresh_install == true